version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: banreservas
    ports:
      - "3306:3306"
    networks:
      - banreservas_network

  user-service:
    build: ./user
    container_name: user-service
    environment:
      NODE_ENV: dev
      DB_HOST: mysql-user
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: "rootpassword"
      DB_NAME: banreservas
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    networks:
      - banreservas_network

  product-service:
    build: ./product
    container_name: product-service
    environment:
      NODE_ENV: dev
      DB_HOST: mysql-user
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: "rootpassword"
      DB_NAME: banreservas
      KAFKA_BROKER: kafka-broker:9093
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - kafka
    networks:
      - banreservas_network

  inventory-service:
    build: ./inventory
    container_name: inventory-service
    environment:
      NODE_ENV: dev
      DB_HOST: mysql-user
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: "rootpassword"
      DB_NAME: banreservas
      KAFKA_BROKER: kafka-broker:9093
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "6000:6000"
    depends_on:
      - mysql
      - kafka
      - redis
    networks:
      - banreservas_network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-broker
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-broker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - banreservas_network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - banreservas_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - banreservas_network

networks:
  banreservas_network:
    driver: bridge
