# Usa Node.js como base (ajustado a la versión que usas)
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos necesarios para instalar dependencias
COPY package.json package-lock.json ./

# Instala las dependencias de la aplicación
RUN npm install

# Copia el resto del código fuente
COPY . .

# Expone el puerto en el que corre tu NestJS app (ajústalo si es necesario)
EXPOSE 3000

# Comando para correr la aplicación
CMD ["npm", "run", "start"]
